name: CI-Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go 1.x.x
      uses: actions/setup-go@v3
      with:
        go-version: 1.19.5
      id: go

    - name: Checkout code in go module directory
      uses: actions/setup-go@v3

    - name: Test
      run: make test